# Generated by Django 3.2.6 on 2021-08-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_remove_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='notes here...'),
        ),
    ]
